name: Backtest CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * 0"

jobs:
  run-backtest:
    runs-on: ubuntu-latest
    env:
      STABLE_TAG: sand1k/zipline-backtest-img:latest
      AWS_SERVER_PUBLIC_KEY: ${{ secrets.AWS_SERVER_PUBLIC_KEY }}
      AWS_SERVER_SECRET_KEY: ${{ secrets.AWS_SERVER_SECRET_KEY }}
      NASDAQ_API_KEY: ${{ secrets.NASDAQ_API_KEY }}
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Run tests
      run: |
        docker run --rm -e AWS_SERVER_PUBLIC_KEY -e AWS_SERVER_SECRET_KEY -e NASDAQ_API_KEY ${{ env.STABLE_TAG }}
